version: 0.2

env:
  variables:
    S3_BUCKET: "rc-bucket-789796897"

phases:
  install:
    runtime-versions:
      golang: 1.24
    commands:
      - echo Installing dependencies...
      - go mod tidy

  pre_build:
    commands:
      - echo Running go vet for static analysis...
      - go vet ./...

  build:
    commands:
      - echo Running Unit Tests
      - go test ./...
      - echo Compiling Go binary...
      - go build -o demo-web-app .

  post_build:
    commands:
      # Derive a release candidate label
      - echo Tagging release candidate...
#      - VERSION=$(git rev-parse --short HEAD)
#      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
#      - RC_TAG=rc-${VERSION}-${TIMESTAMP}
#      - echo "RC Tag: $RC_TAG"
      - echo Uploading binary to S3...
#      - aws s3 cp demo-web-app s3://$S3_BUCKET/releases/$RC_TAG/demo-web-app
      - aws s3 cp demo-web-app s3://$S3_BUCKET/releases/v0.0.1/demo-web-app

artifacts:
  files:
    - demo-web-app
